require:
  - rubocop-performance

AllCops:
  Exclude:
    - app/controllers/devise_token_auth/*
    - bin/*
    - vendor/**/*
    - db/**/*
    - spec/**/*
    - lib/tasks/**/*
    - config/routes.rb
    - config/environments/**/*
    - config/initializers/**/*
Metrics/MethodLength:
  Max: 30
Metrics/LineLength:
  Max: 150
Metrics/AbcSize:
  Max: 30
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EvalWithLocation:
  Enabled: false
Naming/ConstantName:
  Enabled: false
MethodDefParentheses:
  EnforcedStyle: require_parentheses

